### PR TITLE
gracefully handle terminal resize errors

### LINKED ISSUE #687: Uncaught Error: The pty doesn't appear to exist
[Enter steps to reproduce:]

1. Pressed F5 to run a very long script file with self-made packages/modules etc.
2. After long time with no response, tried to stop Julia, but this error message appeared.

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.12.0

### Stack Trace

Uncaught Error: The pty doesn't appear to exist

```
At C:\Users\zpan\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:137

Error: The pty doesn't appear to exist
    at WindowsPtyAgent.resize (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsPtyAgent.js:137:25)
    at /packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:130:26)
    at WindowsTerminal._defer (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:155:24)
    at WindowsTerminal.resize (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:129:14)
    at InkTerminal.resize (/packages/ink/lib/console/console.js:259:17)
    at /packages/ink/lib/console/console.js:63:16
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1214427)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:424586)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:44778)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1214427)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:446919)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:446396)
    at Pane.activate (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:463814)
    at Pane.focus (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:455257)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
    at t.focus (/packages/ink/node_modules/xterm/lib/xterm.js:1:65064)
    at /packages/ink/node_modules/xterm/lib/xterm.js:1:77286)
```

### Commands

```
     -3:43.6.0 julia-debug:run-file (input.hidden-input)
     -0:16 core:backspace (input.hidden-input)
     -0:14.3.0 julia-client:kill-julia (input.hidden-input)
```

### Non-Core Packages

```
atom-debugger 0.1.6 
atom-ide-datatip 0.0.0 
atom-ide-definitions 0.3.3 
atom-ide-markdown-service 1.2.3 
atom-ide-ui 0.13.0 
atom-python-run 0.9.7 
atom-terminal-powershell 1.1.0 
bracket-colorizer 1.4.0 
build-cargo 2.0.0 
busy-signal 2.0.1 
file-icons 2.1.39 
ftp-remote-edit 0.18.0 
git-plus 8.7.1 
git-time-machine 2.1.0 
highlight-line 0.12.0 
highlight-selected 0.17.0 
hyperclick 0.0.0 
ide-rust 0.21.2 
indent-detective 0.4.0 
ink 0.12.0 
intentions 1.1.5 
julia-client 0.12.0 
jumpy 5.0.2 
juno-plus 0.10.2 
language-julia 0.19.2 
language-matlab 0.2.1 
last-cursor-position 0.9.3 
latex-completions 0.3.6 
local-history 4.3.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-quick-highlight 1.0.1 
minimap-selection 4.5.0 
pp-markdown 0.0.2 
project-plus 1.0.0 
python-debugger 0.2.0 
quick-highlight 0.13.0 
script 3.25.0 
split-diff 1.6.1 
sync-settings 2.3.1 
TabNine 2.1.7 
tool-bar 1.2.0 
tree-view-git-status 1.5.2 
uber-juno 0.3.0 
```

### PR DESCRIPTION
**Pull request by pfitzseb**
Should fix https://github.com/JunoLab/atom-julia-client/issues/687.

### CODE REVIEW

File: lib/console/console.js [hunk 1]
```diff
@@ -258,10 +258,16 @@ export default class InkTerminal extends PaneItem {
...
+    if (cols < 1) cols = 1
     if (this.terminal && !isNaN(cols) && !isNaN(rows)) {
       this.terminal.resize(cols, rows)
       if (this.ty && this.ty.resize) {
-        this.ty.resize(cols, rows)
+        try {
+          this.ty.resize(cols, rows)
+        } catch (err) {
+          // the pty can apparently die before the resize event goes through (https://github.com/JunoLab/atom-julia-client/issues/687)
+          console.error(er)
```
Comment (aviatesk) [inline lib/console/console.js]:
```suggestion
          console.error(err)
```

**Review by aviatesk — CHANGES_REQUESTED** [review]
